### ISSUE TITLE
Add Console Responses

### ISSUE THREAD

**Issue by aggelosQQ** [Adaptified/Freedom#3]
When casting commands from console, errors just pop-up.

```
:[02:35:24 ERROR]: [Freedom] Uncaught exception executing command: cmdspy
:[02:35:24 ERROR]: [Freedom] java.lang.ClassCastException: me.totalfreedom.bukkittelnet.session.SessionCommandSender cannot be cast to org.bukkit.entity.Player
    at me.adapt.freedom.cmds.CMD_cmdspy.onCommand(CMD_cmdspy.java:28)
    at net.pravian.aero.command.SimpleCommand.runCommand(SimpleCommand.java:39)
    at net.pravian.aero.command.executor.SimpleCommandExecutor.onCommand(SimpleCommandExecutor.java:62)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645)
    at me.totalfreedom.bukkittelnet.session.ClientSession$1.run(ClientSession.java:198)
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729)
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
    at java.lang.Thread.run(Thread.java:745)
:Command error: me.totalfreedom.bukkittelnet.session.SessionCommandSender cannot be cast to org.bukkit.entity.Player
```

You should add some `if``s that will check if the sender is console and echo the proper response.

**Comment by mgejay** [comment]
Will fix.
